name: Publish to Docker Hub
on: 
  push:
    branches:
      - windows

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish (${{ matrix.tag }})
    strategy:
      matrix:
        include:
          - target: linux
            platform: linux/amd64
            tag: linux-amd64
          - target: linux
            platform: linux/arm64
            tag: linux-arm64
          - target: windows
            platform: windows/amd64
            tag: windows-amd64-2004
            base: mcr.microsoft.com/windows/nanoserver:2004
          - target: windows
            platform: windows/amd64
            tag: windows-amd64-20H2
            base: mcr.microsoft.com/windows/nanoserver:20H2
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: ${{ matrix.platform }}
          target: ${{ matrix.target }}
          build-args: WINBASE=${{ ( matrix.base != '' && matrix.base ) || 'scratch' }}
          push: true
          tags: mergermarket/cdflow2-build-docker-ecr:cross-${{ matrix.tag }}

  create-manifest:
    runs-on: ubuntu-latest
    name: Create manifest
    needs: [publish]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Create latest manifest and push
        run: |
          docker manifest create \
            mergermarket/cdflow2-build-docker-ecr:cross \
              mergermarket/cdflow2-build-docker-ecr:cross-linux-amd64 \
              mergermarket/cdflow2-build-docker-ecr:cross-linux-arm64 \
              mergermarket/cdflow2-build-docker-ecr:cross-windows-amd64-2004 \
              mergermarket/cdflow2-build-docker-ecr:cross-windows-amd64-20H2
          docker manifest push mergermarket/cdflow2-build-docker-ecr:cross
